pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
               git branch: 'main', credentialsId: 'github', url: 'https://github.com/yj1910/Jenkins-Zero-To-Hero.git'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    cd python-jenkins-argocd-k8s
                    echo 'Buid Docker Image'
                    docker build -t yjain75/demo:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('login & Push the artifacts'){
            environment {
                DOCKER_IMAGE = "yjain75/demo:${BUILD_NUMBER}"
                REGISTRY_CREDENTIALS = credentials('docker')
              }
              steps {
                script {
                    sh ''' 
                    docker build -t ${DOCKER_IMAGE} .
                    echo 'push to repo'
                    '''
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry('https://index.docker.io/v1/', "docker") {
                    dockerImage.push()
            }
        }
      }
        }
        

        
    }
}
